-- Сгенерировано scripts/gen-seed-sql.ts — не редактировать вручную (npm run gen:seed).
-- Идемпотентно: повторный запуск не дублирует данные.

-- Зоны: A «Поговорить» 60–65 дБ, B «Фон» 65–72 дБ, C «Движ» 72–80 дБ
insert into public.zones (id, name, target_min_db, target_max_db, music_volume, tempo, auto_mode, music_ref_db, music_ref_volume) values ('A', 'Поговорить', 60, 65, 0.6, 'mid', true, 60, 0.6) on conflict (id) do nothing;
insert into public.zones (id, name, target_min_db, target_max_db, music_volume, tempo, auto_mode, music_ref_db, music_ref_volume) values ('B', 'Фон', 65, 72, 0.65, 'mid', true, 64, 0.65) on conflict (id) do nothing;
insert into public.zones (id, name, target_min_db, target_max_db, music_volume, tempo, auto_mode, music_ref_db, music_ref_volume) values ('C', 'Движ', 72, 80, 0.75, 'fast', true, 71, 0.75) on conflict (id) do nothing;

-- План зала: 41 стол, 200 мест
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (1, 'A', 4, 75, 140, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (2, 'A', 4, 165, 140, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (3, 'A', 4, 255, 140, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (4, 'A', 4, 75, 240, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (5, 'A', 2, 165, 240, 32, 32, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (6, 'A', 2, 255, 240, 32, 32, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (7, 'A', 6, 75, 340, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (8, 'A', 6, 165, 340, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (9, 'A', 4, 255, 340, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (10, 'A', 4, 75, 440, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (11, 'A', 2, 165, 440, 32, 32, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (12, 'A', 2, 255, 440, 32, 32, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (13, 'A', 6, 110, 545, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (14, 'A', 6, 220, 545, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (15, 'B', 4, 395, 130, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (16, 'B', 4, 495, 130, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (17, 'B', 4, 595, 130, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (18, 'B', 6, 395, 220, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (19, 'B', 6, 495, 220, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (20, 'B', 6, 595, 220, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (21, 'B', 8, 430, 310, 84, 42, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (22, 'B', 8, 565, 310, 84, 42, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (23, 'B', 4, 395, 400, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (24, 'B', 4, 495, 400, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (25, 'B', 4, 595, 400, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (26, 'B', 6, 395, 490, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (27, 'B', 4, 495, 490, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (28, 'B', 2, 595, 490, 32, 32, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (29, 'B', 2, 395, 580, 32, 32, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (30, 'B', 4, 495, 580, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (31, 'C', 6, 725, 130, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (32, 'C', 6, 840, 130, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (33, 'C', 4, 725, 220, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (34, 'C', 4, 840, 220, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (35, 'C', 8, 725, 310, 84, 42, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (36, 'C', 8, 840, 310, 84, 42, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (37, 'C', 6, 725, 400, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (38, 'C', 6, 840, 400, 64, 38, 'rect') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (39, 'C', 4, 725, 490, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (40, 'C', 4, 840, 490, 44, 44, 'round') on conflict (table_no) do nothing;
insert into public.hall_tables (table_no, zone_id, seats, x, y, w, h, shape) values (41, 'C', 12, 950, 375, 36, 430, 'bar') on conflict (table_no) do nothing;

-- Комнаты Table Mode для столов 1–12
insert into public.rooms (table_no, phase, state) values (1, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (2, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (3, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (4, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (5, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (6, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (7, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (8, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (9, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (10, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (11, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;
insert into public.rooms (table_no, phase, state) values (12, 'idle', '{}'::jsonb) on conflict (table_no) do nothing;

-- Библиотека контента: 30 вопросов, 25 миссий, 5 миссий с персоналом
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-01', 'question', 'any', 'ru', 'Кто из нас мог бы вести собственное кулинарное шоу?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-02', 'question', 'any', 'ru', 'Кто из нас лучше всех рассказывает истории?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-03', 'question', 'any', 'ru', 'Кто из нас быстрее всех выучит новый язык, если переедет в другую страну?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-04', 'question', 'any', 'ru', 'Кто из нас продержался бы на необитаемом острове дольше всех?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-05', 'question', 'any', 'ru', 'Кто из нас лучше всех поддержит в трудную минуту?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-06', 'question', 'any', 'ru', 'Кто из нас чаще опаздывает — зато с самыми изобретательными оправданиями?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-07', 'question', 'any', 'ru', 'Кто из нас скорее всего напишет книгу?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-08', 'question', 'any', 'ru', 'Кто из нас первым выйдет танцевать на празднике?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-09', 'question', 'any', 'ru', 'Кто из нас никогда не забывает про дни рождения друзей?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-10', 'question', 'any', 'ru', 'Кто из нас стал бы лучшим ведущим вечерних новостей?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-11', 'question', 'any', 'ru', 'Кто из нас скорее всего отправится в кругосветное путешествие?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-12', 'question', 'any', 'ru', 'Кто из нас дольше всех выбирает блюдо в меню?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-13', 'question', 'any', 'ru', 'Кто из нас первым предложит сделать общее фото?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-14', 'question', 'any', 'ru', 'Кто из нас смеётся заразительнее всех?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-15', 'question', 'any', 'ru', 'Кто из нас стал бы лучшим капитаном корабля в шторм?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-16', 'question', 'any', 'ru', 'Кто из нас первым пробует незнакомое блюдо?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-17', 'question', 'any', 'ru', 'Кто из нас выиграл бы телевикторину?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-18', 'question', 'any', 'ru', 'Кто из нас сохраняет спокойствие в любой ситуации?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-19', 'question', 'any', 'ru', 'Кто из нас скорее всего откроет собственное кафе?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-20', 'question', 'any', 'ru', 'Кто из нас даёт самые точные советы?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-21', 'question', 'any', 'ru', 'Кто из нас помнит самые смешные моменты нашей компании?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-22', 'question', 'any', 'ru', 'Кто из нас мог бы стать лучшим гидом по родному городу?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-23', 'question', 'meetup', 'ru', 'Кто из нас придумает лучший план на ближайшие выходные?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-24', 'question', 'meetup', 'ru', 'Кто из нас первым предложил собраться сегодня?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-25', 'question', 'birthday', 'ru', 'Кто из нас лучше всех знает именинника?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-26', 'question', 'birthday', 'ru', 'Кто из нас подарил бы имениннику самый неожиданный подарок?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-27', 'question', 'reunion', 'ru', 'Кто из нас сильнее всех изменился с нашей последней встречи?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-28', 'question', 'reunion', 'ru', 'Кто из нас первым напишет в общий чат после этой встречи?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-29', 'question', 'success', 'ru', 'Кто из нас внёс самый незаметный, но важный вклад в общий успех?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-q-30', 'question', 'success', 'ru', 'Кто из нас станет героем следующей большой победы?', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-01', 'mission', 'any', 'ru', 'Сделай так, чтобы трое за столом сказали слово «отлично».', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-02', 'mission', 'any', 'ru', 'Незаметно сделай искренний комплимент каждому за столом.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-03', 'mission', 'any', 'ru', 'Заведи разговор о путешествиях — пусть каждый назовёт город мечты.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-04', 'mission', 'any', 'ru', 'Трижды за вечер вверни фразу «как говорила моя бабушка».', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-05', 'mission', 'any', 'ru', 'Добейся, чтобы кто-нибудь рассказал историю из детства.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-06', 'mission', 'any', 'ru', 'Незаметно поменяй местами два предмета на столе.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-07', 'mission', 'any', 'ru', 'Трижды повтори жест соседа так, чтобы он не заметил.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-08', 'mission', 'any', 'ru', 'Узнай у каждого его любимое блюдо из детства.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-09', 'mission', 'any', 'ru', 'Пять раз упомяни в разговоре название любого фильма.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-10', 'mission', 'any', 'ru', 'Добейся, чтобы вся компания одновременно рассмеялась.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-11', 'mission', 'any', 'ru', 'Задай три вопроса подряд, на которые тебе ответят «да».', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-12', 'mission', 'any', 'ru', 'Сделай так, чтобы кто-нибудь напел строчку из песни.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-13', 'mission', 'any', 'ru', 'Добейся, чтобы кто-нибудь трижды назвал тебя по имени.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-14', 'mission', 'any', 'ru', 'Сложи из салфетки фигурку и оставь её на виду.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-15', 'mission', 'any', 'ru', 'Дважды начни фразу с «А вы знали, что…» и расскажи интересный факт.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-16', 'mission', 'any', 'ru', 'Похвали блюдо так, будто ты ресторанный критик.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-17', 'mission', 'any', 'ru', 'Три минуты начинай каждую реплику со слова «кстати».', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-18', 'mission', 'any', 'ru', 'Добейся, чтобы сосед справа рассказал о своём хобби.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-19', 'mission', 'any', 'ru', 'Устрой мини-голосование за столом по любому поводу.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-20', 'mission', 'any', 'ru', 'Узнай, кто за столом умеет свистеть, — не спрашивая напрямую.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-21', 'mission', 'any', 'ru', 'Добейся, чтобы все одновременно посмотрели в одну сторону.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-22', 'mission', 'any', 'ru', 'Вставь в разговор три слова на другом языке.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-23', 'mission', 'any', 'ru', 'Придумай столу название и добейся, чтобы его подхватили.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-24', 'mission', 'birthday', 'ru', 'Незаметно узнай у именинника, о чём он мечтает в этом году.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-m-25', 'mission', 'success', 'ru', 'Добейся, чтобы герой вечера рассказал, с чего всё началось.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-s-01', 'staff_mission', 'any', 'ru', 'Узнай у бармена, какой коктейль из меню он любит больше всего.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-s-02', 'staff_mission', 'any', 'ru', 'Спроси официанта, какое блюдо он посоветовал бы тому, кто здесь впервые.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-s-03', 'staff_mission', 'any', 'ru', 'Узнай у персонала, какой десерт здесь заказывают чаще всего.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-s-04', 'staff_mission', 'any', 'ru', 'Узнай у официанта, есть ли у ресторана своя история или легенда.', true, 'seed') on conflict (id) do nothing;
insert into public.content_library (id, type, occasion, lang, text, approved, source) values ('seed-s-05', 'staff_mission', 'any', 'ru', 'Спроси у персонала, что за музыка сейчас играет в зале.', true, 'seed') on conflict (id) do nothing;
